use mc_server_wrapper_core::config_files::json::*;
use mc_server_wrapper_core::config_files::properties::*;
use mc_server_wrapper_core::config_files::toml::*;
use mc_server_wrapper_core::config_files::yaml::*;
use std::collections::HashMap;
use serde_json::json;
use serde_json::Value as JsonValue;
use toml::Value as TomlValue;
use serde_yaml::Value as YamlValue;

#[test]
fn test_flatten_json() {
    let data = json!({
        "a": 1,
        "b": {
            "c": "hello",
            "d": [1, 2]
        }
    });
    let mut props = HashMap::new();
    flatten_json("", &data, &mut props);
    assert_eq!(props.get("a").unwrap(), "1");
    assert_eq!(props.get("b.c").unwrap(), "hello");
    assert_eq!(props.get("b.d[0]").unwrap(), "1");
    assert_eq!(props.get("b.d[1]").unwrap(), "2");
}

#[test]
fn test_unflatten_json() {
    let mut map = serde_json::Map::new();
    unflatten_json(&mut map, "a.b.c", "val".to_string());
    unflatten_json(&mut map, "a.d", "true".to_string());
    let root = JsonValue::Object(map);
    assert_eq!(root["a"]["b"]["c"], "val");
    assert_eq!(root["a"]["d"], true);
}

#[test]
fn test_parse_properties() {
    let content = "key1=value1\n# comment\n  key2 = value2  \n\nkey3=value3";
    let props = parse_properties(content);
    assert_eq!(props.get("key1").unwrap(), "value1");
    assert_eq!(props.get("key2").unwrap(), "value2");
    assert_eq!(props.get("key3").unwrap(), "value3");
    assert_eq!(props.len(), 3);
}

#[test]
fn test_parse_properties_as_json() {
    let content = "key1=value1\nkey2=true";
    let json = parse_properties_as_json(content);
    assert_eq!(json["key1"], "value1");
    assert_eq!(json["key2"], "true");
}

#[test]
fn test_serialize_properties() {
    let mut props = HashMap::new();
    props.insert("a".to_string(), "1".to_string());
    props.insert("b".to_string(), "2".to_string());
    let serialized = serialize_properties(&props);
    assert!(serialized.contains("a=1"));
    assert!(serialized.contains("b=2"));
    assert!(serialized.contains("# Generated by MC Server Wrapper"));
}

#[test]
fn test_serialize_json_as_properties() {
    let json = serde_json::json!({
        "key1": "value1",
        "key2": 123
    });
    let serialized = serialize_json_as_properties(&json);
    assert!(serialized.contains("key1=value1"));
    assert!(serialized.contains("key2=123"));
}

#[test]
fn test_flatten_toml() {
    let content = r#"
        a = 1
        [b]
        c = "hello"
        d = [1, 2]
    "#;
    let data: TomlValue = toml::from_str(content).unwrap();
    let mut props = HashMap::new();
    flatten_toml("", &data, &mut props);
    assert_eq!(props.get("a").unwrap(), "1");
    assert_eq!(props.get("b.c").unwrap(), "hello");
    assert_eq!(props.get("b.d[0]").unwrap(), "1");
    assert_eq!(props.get("b.d[1]").unwrap(), "2");
}

#[test]
fn test_unflatten_toml() {
    let mut map = toml::map::Map::new();
    unflatten_toml(&mut map, "a.b.c", "val".to_string());
    unflatten_toml(&mut map, "a.d", "123".to_string());
    let root = TomlValue::Table(map);
    assert_eq!(root.get("a").unwrap().get("b").unwrap().get("c").unwrap().as_str().unwrap(), "val");
    assert_eq!(root.get("a").unwrap().get("d").unwrap().as_integer().unwrap(), 123);
}

#[test]
fn test_flatten_yaml() {
    let content = r#"
        a: 1
        b:
          c: hello
          d: [1, 2]
    "#;
    let data: YamlValue = serde_yaml::from_str(content).unwrap();
    let mut props = HashMap::new();
    flatten_yaml("", &data, &mut props);
    assert_eq!(props.get("a").unwrap(), "1");
    assert_eq!(props.get("b.c").unwrap(), "hello");
    assert_eq!(props.get("b.d[0]").unwrap(), "1");
    assert_eq!(props.get("b.d[1]").unwrap(), "2");
}

#[test]
fn test_unflatten_yaml() {
    let mut map = serde_yaml::Mapping::new();
    unflatten_yaml(&mut map, "a.b.c", "val".to_string());
    unflatten_yaml(&mut map, "a.d", "true".to_string());
    let root = YamlValue::Mapping(map);
    assert_eq!(root["a"]["b"]["c"], YamlValue::String("val".to_string()));
    assert_eq!(root["a"]["d"], YamlValue::Bool(true));
}
