use std::collections::HashMap;
use serde_json::{Value as JsonValue, Map};

/// Logic for .properties files
pub fn parse_properties(content: &str) -> HashMap<String, String> {
    let mut props = HashMap::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            props.insert(key.trim().to_string(), value.trim().to_string());
        }
    }
    props
}

pub fn parse_properties_as_json(content: &str) -> JsonValue {
    let mut map = Map::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            map.insert(key.trim().to_string(), JsonValue::String(value.trim().to_string()));
        }
    }
    JsonValue::Object(map)
}

pub fn serialize_properties(properties: &HashMap<String, String>) -> String {
    let mut content = String::new();
    content.push_str("# Generated by MC Server Wrapper\n");
    let mut keys: Vec<_> = properties.keys().collect();
    keys.sort();
    for key in keys {
        if let Some(value) = properties.get(key) {
            content.push_str(&format!("{}={}\n", key, value));
        }
    }
    content
}

pub fn serialize_json_as_properties(value: &JsonValue) -> String {
    let mut content = String::new();
    content.push_str("# Generated by MC Server Wrapper\n");
    if let JsonValue::Object(map) = value {
        let mut keys: Vec<_> = map.keys().collect();
        keys.sort();
        for key in keys {
            if let Some(val) = map.get(key) {
                let val_str = match val {
                    JsonValue::String(s) => s.clone(),
                    _ => val.to_string(),
                };
                content.push_str(&format!("{}={}\n", key, val_str));
            }
        }
    }
    content
}
